name: 'Terraform Actions Collection'
description: 'Terraform Actions Collection for Github'
author: 'drew.mercer'
inputs:
  ACTION:
    description: 'Action to run'
    required: true
  TERRAFORM_VERSION:
    description: 'Terraform Version'
    required: true
  DIRECTORY: 
    description: 'Directory to run Terraform in'
    required: true
  GITHUB_TOKEN: 
    description: 'Github Token'
    required: true
  ENVIRONMENT: 
    description: 'Environment'
    required: false
  GITHUB_REPOSITORY:
    description: 'Github Repository'
    required: false
  GITHUB_SHA:
    description: 'Github SHA'
    required: false
  GITHUB_ISSUE:
    description: 'Github Event'
    required: false
  NPM_TOKEN: 
    description: 'NPM Token'
    required: false
  GITHUB_APP_CLOUDBUILD_INSTALLATION_ID: 
    description: 'Github App Cloud Build Installation ID'
    required: false
  CLOUDFLARE_API_TOKEN: 
    description: 'Cloudflare API Token'
    required: false
  DATADOG_API_KEY: 
    description: 'Datadog API Key'
    required: false
  DATADOG_APP_KEY: 
    description: 'Datadog App Key'
    required: false
  DATADOG_PRINCIPAL_ACCOUNT:
    description: 'Datadog Principal Account'
    required: false

runs:
  using: "composite"
  steps:
  - uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ inputs.TERRAFORM_VERSION}}

  - id: init
    run: |
      terraform -chdir=${{ inputs.directory }} init
    shell: bash

  - name: terraform init status
    if: steps.init.outcome == 'failure' 
    run: |
      exit 1
    shell: bash

  - id: lint
    run: |
      terraform -chdir=${{ inputs.directory }} fmt -check -diff -recursive .
    shell: bash

  - name: verify terraform lint
    if: steps.lint.outcome == 'failure'
    run: |
      exit 1
    shell: bash

  - name: validate
    run: |
      terraform -chdir=${{ inputs.directory }} validate -no-color
    shell: bash

  - name: verify terraform validate
    if: steps.validate.outcome == 'failure'
    run: |
      exit 1
    shell: bash

  - id: plan
    continue-on-error: true
    env:
      TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
      TF_VAR_ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      TF_VAR_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      TF_VAR_GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY }}
      TV_VAR_GITHUB_SHA: ${{ inputs.GITHUB_SHA }}
      TF_VAR_NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      TF_VAR_GITHUB_APP_CLOUDBUILD_INSTALLATION_ID: ${{ inputs.GITHUB_APP_CLOUDBUILD_INSTALLATION_ID }}
      TF_VAR_CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
      TF_VAR_DATADOG_API_KEY: ${{ inputs.DATADOG_API_KEY }}
      TF_VAR_DATADOG_APP_KEY: ${{ inputs.DATADOG_APP_KEY }}
      TF_VAR_DATADOG_PRINCIPAL_ACCOUNT: ${{ inputs.DATADOG_PRINCIPAL_ACCOUNT }}
    run: |
      set +e
      cd ${{ inputs.directory }} && \
      terraform plan -input=false -no-color -out=tfplan
      terraform show -no-color tfplan
    shell: bash

  - name: verify terraform plan
    if: steps.plan.outcome == 'failure'
    run: |
      echo "terraform plan failed"
      exit 1
    shell: bash

  - id: plan_output
    if: inputs.ACTION == 'plan'
    run: |
      echo -e '## ${{ inputs.DIRECTORY }} plan\n' > ${{ inputs.DIRECTORY }}/plan.txt
      echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
      | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' >> ${{ inputs.DIRECTORY }}/plan.txt
      PLAN=$(cat ${{ inputs.DIRECTORY }}/plan.txt)
      echo "PLAN<<EOF" >> $GITHUB_OUTPUT
      echo "$PLAN" >> $GITHUB_OUTPUT
      echo "EOF" >> $GITHUB_OUTPUT
    shell: bash
      
  - id: plan_delta
    if: inputs.ACTION == 'plan'
    run: |
      if grep -Fxq "No changes. Your infrastructure matches the configuration." ${{ inputs.DIRECTORY }}/plan.txt
      then
          echo "post_plan=false" >> $GITHUB_OUTPUT
      else
          echo "post_plan=true" >> $GITHUB_OUTPUT
      fi
    shell: bash

  - uses: mshick/add-pr-comment@v2
    if: steps.plan_delta.outputs.post_plan == 'true'
    id: post_plan
    with:
      allow-repeats: true
      repo-token: ${{ inputs.GITHUB_TOKEN }}
      repo-token-user-login: 'github-actions[bot]'
      message: |
            ## ${{ inputs.DIRECTORY }}
            ```diff
            ${{ steps.plan_output.outputs.plan }}
            ```

  - id: apply
    if: inputs.ACTION == 'apply'
    continue-on-error: true
    run: |
      terraform -chdir=${{ inputs.directory }} apply \
        -input=false \
        -no-color \
        tfplan
    shell: bash

  - if: steps.apply.outcome == 'failure' 
    run: |
      echo "terraform apply failed"
      exit 1
    shell: bash

