name: 'Terraform Actions Collection'
description: 'Run actions for Terraform Project'
author: 'drew.mercer'
inputs:
  ACTION:
    description: 'Action to run'
    required: true
  TERRAFORM_VERSION:
    description: 'Terraform Version'
    required: true
  PROJECT_ID: 
    description: 'Project ID'
    required: true
  GITHUB_TOKEN: 
    description: 'Github Token'
    required: true
  NPM_TOKEN: 
    description: 'NPM Token'
    required: true
  GITHUB_APP_CLOUDBUILD_INSTALLATION_ID: 
    description: 'Github App Cloud Build Installation ID'
    required: true
  CLOUDFLARE_API_TOKEN: 
    description: 'Cloudflare API Token'
    required: true
  DATADOG_API_KEY: 
    description: 'Datadog API Key'
    required: true
  DATADOG_APP_KEY: 
    description: 'Datadog App Key'
    required: true
  DIRECTORY: 
    description: 'Directory to run Terraform in'
    required: true

runs:
  using: "composite"
  steps:
  - uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: ${{ inputs.TERRAFORM_VERSION}}

  - id: init
    run: |
      terraform -chdir=${{ inputs.directory }} init
      terraform -chdir=${{ inputs.directory }} validate -no-color
      terraform -chdir=${{ inputs.directory }} fmt -check -diff -recursive .
    shell: bash

  - if: steps.init.outcome == 'failure' 
    run: |
      exit 1
    shell: bash

  - id: plan
    if: inputs.ACTION == 'plan'
    continue-on-error: true
    env:
      TERRAFORM_VERSION: ${{ inputs.TERRAFORM_VERSION }}
      TF_VAR_PROJECT_ID: ${{ inputs.PROJECT_ID }}
      TF_VAR_GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      TF_VAR_NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      TF_VAR_GITHUB_APP_CLOUDBUILD_INSTALLATION_ID: ${{ inputs.GITHUB_APP_CLOUDBUILD_INSTALLATION_ID }}
      TF_VAR_CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
      TF_VAR_DATADOG_API_KEY: ${{ inputs.DATADOG_API_KEY }}
      TF_VAR_DATADOG_APP_KEY: ${{ inputs.DATADOG_APP_KEY }}
    run: |
      cd ${{ inputs.directory }} && \
      terraform plan -input=false -no-color -out=tfplan && \
      terraform show -no-color tfplan
    shell: bash

  - if: steps.plan.outcome == 'failure' && inputs.ACTION == 'plan'
    run: |
      exit 1
    shell: bash

  - run: |
      echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
      | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt
    shell: bash

  - run: |
      PLAN=$(cat plan.txt)
      echo "PLAN<<EOF" >> $GITHUB_ENV
      echo "$PLAN" >> $GITHUB_ENV
      echo "EOF" >> $GITHUB_ENV
    shell: bash

  - uses: mshick/add-pr-comment@v1
    if: inputs.ACTION == 'plan'
    with:
      allow-repeats: true
      repo-token: ${{ inputs.GITHUB_TOKEN }}
      repo-token-user-login: 'github-actions[bot]'
      message: |
        ## ${{ inputs.directory }} plan
        ```diff
        ${{ env.PLAN }}
        ```

  - id: apply
    if: inputs.ACTION == 'apply'
    continue-on-error: true
    run: |
      terraform -chdir=${{ inputs.directory }} apply \
        -input=false \
        -no-color \
        tfplan
    shell: bash

  - id: post_plan
    if: steps.plan.outcome == 'success' && steps.apply.outcome == 'success'
    uses: mshick/add-pr-comment@v1
    with:
      repo-token: ${{ inputs.GITHUB_TOKEN }}
      repo-token-user-login: 'github-actions[bot]'
      message: |
        Applying **${{ inputs.directory }}**:

        ```diff
        ${{ env.PLAN }}
        ```

        ```
        ${{ steps.apply.outputs.stdout }}
        ```

  - if: steps.plan.outcome == 'failure' && inputs.ACTION == 'apply'
    uses: mshick/add-pr-comment@v1
    with:
      repo-token: ${{ inputs.GITHUB_TOKEN }}
      repo-token-user-login: 'github-actions[bot]'
      message: |
        Plan failed for **${{ inputs.directory }}**:

        ```
        ${{ steps.plan.outputs.stderr }}
        ```
      run: exit 1
      shell: bash

  - if: steps.apply.outcome == 'failure' 
    uses: mshick/add-pr-comment@v1
    with:
      repo-token: ${{ inputs.GITHUB_TOKEN }}
      repo-token-user-login: 'github-actions[bot]'
      message: |
        Apply failed for **${{ inputs.directory }}**:

        ```
        ${{ steps.apply.outputs.stderr }}
        ```
      run: exit 1
      shell: bash
