name: Dependabot Jira Integration

on:
  pull_request_target:
    branches:
      - main # Or your default branch (e.g., main, master)

jobs:
  create_jira_tickets:
    if: github.actor == 'dependabot[bot]' # Only run for Dependabot PRs
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: "${{ secrets.JIRA_GH_TOKEN }}"
          skip-commit-verification: true
          skip-verification: true

      - name: Issue Classification
        id: issue-classification
        run: |
          echo "CVSS score: ${{ steps.dependabot-metadata.outputs.cvss }}"
          if [ "${{ steps.dependabot-metadata.outputs.cvss }}" < "4" ]; then
            echo "CVSS score is less than 4.0"
            echo "class=Low" >> "$GITHUB_OUTPUT"
            echo "priority=2" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.dependabot-metadata.outputs.cvss }}" < "7" ]; then
            echo "CVSS score is between 4.0 and 7.0"
            echo "class=Medium" >> "$GITHUB_OUTPUT"
            echo "priority=3" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.dependabot-metadata.outputs.cvss }}" < "9" ]; then
            echo "CVSS score is greater than or equal to 7.0"
            echo "class=High" >> "$GITHUB_OUTPUT"
            echo "priority=4" >> "$GITHUB_OUTPUT"
          else
            echo "CVSS score is greater than or equal to 9.0"
            echo "class=Critical" >> "$GITHUB_OUTPUT"
            echo "priority=5" >> "$GITHUB_OUTPUT"
          fi

      - name: Description Formatter
        id: description-formatter
        run: |
          description=$(cat << EOF
          Dependabot has created a pull request to update dependencies.
          PR: ${{ github.event.pull_request.html_url }}
          Branch: ${{ github.head_ref }}
          Repository: ${{ github.repository }}
          CVSS Classification: ${{ steps.issue-classification.outputs.class }}
          CVSS Score: ${{ steps.dependabot-metadata.outputs.cvss }}
          To confirm the fix, apply the patch and provide testing steps to verify no existing features are broken.
          EOF
          )
          description="${description//$'\n'/'\\n'}"
          echo "description=$description" >> "$GITHUB_OUTPUT"
          
      - name: Create Jira Ticket
        uses: brandlive1941/action-jira-integration@jira_action  # Use the latest version
        with:
          action: "create"
          token: ${{ secrets.JIRA_TOKEN }} # Store your Jira API token in GitHub Secrets
          jira_url: ${{ vars.JIRA_URL }}
          project: ${{ vars.JIRA_PROJECT }} # Replace with your Jira project key
          summary: "${{ steps.issue-classification.outputs.class }} [Dependabot] Security update for ${{ github.repository }}" 
          description: "${{ steps.description-formatter.outputs.description }}"
          priority: ${{ steps.issue-classification.outputs.priority }} # Or "High", "Low", etc.