name: Dependabot Jira Integration

on:
  pull_request_target:
    branches:
      - main # Or your default branch (e.g., main, master)
  workflow_dispatch:

jobs:
  create_jira_tickets:
    if: github.actor == 'dependabot[bot]' # Only run for Dependabot PRs
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: "${{ secrets.JIRA_GH_TOKEN }}"
          skip-commit-verification: true
          skip-verification: true

      - uses: actions/github-script@v7
        id: get-severity
        with:
          github-token: "${{ secrets.JIRA_GH_TOKEN }}"
          result-encoding: string
          retries: 3
          retry-exempt-status-codes: 400,401
          script: |
            const alerts = await github.rest.dependabot.listAlertsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            });

            let severity = null;
            console.log(`Dependency names: ${{ steps.dependabot-metadata.outputs.dependency-names }}`);
            let dependencyNames = ${{ steps.dependabot-metadata.outputs.dependency-names }}.split(',').map(name => name.trim());
            for (const alert of alerts.data) {
              console.log(`Checking alert for dependency: ${alert.dependency.package.name}`);
              if (alert.dependency.package.name.includes(dependencyNames)) {
                
                severity = alert.severity;
                break;
              }
            }

            if (severity !== null) {
              return { severity };
            } else {
              throw new Error("No matching Dependabot alert found for the given dependencies.");
            }

      - name: Description Formatter
        id: description-formatter
        run: |
          description=$(cat << EOF
          Dependabot has created a pull request to update dependencies.
          PR: ${{ github.event.pull_request.html_url }}
          Branch: ${{ github.head_ref }}
          Repository: ${{ github.repository }}
          CVSS Classification: ${{ steps.get-severity.outputs.result }}
          CVSS Score: ${{ steps.dependabot-metadata.outputs.cvss }}
          To confirm the fix, apply the patch and provide testing steps to verify no existing features are broken.
          EOF
          )
          description="${description//$'\n'/'\\n'}"
          echo "description=$description" >> "$GITHUB_OUTPUT"
          
      - name: Create Jira Ticket
        uses: brandlive1941/action-jira-integration@jira_action  # Use the latest version
        with:
          action: "create"
          token: ${{ secrets.JIRA_TOKEN }} # Store your Jira API token in GitHub Secrets
          jira_url: ${{ vars.JIRA_URL }}
          project: ${{ vars.JIRA_PROJECT }} # Replace with your Jira project key
          summary: "${{ steps.issue-classification.outputs.class }} [Dependabot] Security update for ${{ github.repository }}" 
          description: "${{ steps.description-formatter.outputs.description }}"
          priority: ${{ steps.get-severity.outputs.result }} # Or "High", "Low", etc.
          label: "dependabot" # Optional: Add a label to the Jira ticket